config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'search#index'
  get '/search/:id', to: 'search#show', as: 'search_show'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
# TODO: implement requests cache in Flickr fu
class SearchController < ApplicationController
  def index
    query = params[:query] || 'random'
    page = params[:page] || 0
    @results = FLICKR.photos.search(text: query, page: page, per_page: 50)
  end

  def show
    @photo = FLICKR.photos.find_by_id(params['id'])
  rescue
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FlickrSearch
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .row
        = yield

app/views/search/_pagination.html.haml
.col-md-12
  %nav
    %ul.pager
      %li
        = link_to 'Previous', request.query_parameters.merge(page: results.page - 1)
      %li
        = link_to 'Next', request.query_parameters.merge(page: results.page + 1)

app/views/search/_preview.html.haml
.col-xs-6.col-md-2
  = link_to search_show_path(id: photo.id ), class: 'thumbnail image_preview', target: '_blank' do
    = image_tag photo.url(:large_square)

app/views/search/_search_form.html.haml
.col-md-6.col-md-offset-3
  %h2 Search photos
  = form_tag root_path, method: :get do
    #custom-search-input
      .input-group.col-md-12
        = text_field_tag 'query', params[:query], placeholder: 'Enter your search query here', class: 'form-control input-lg'
        %span.input-group-btn
          = button_tag(type: 'submit', class: 'btn btn-info btn-lg') do
            %i.glyphicon.glyphicon-search

app/views/search/index.html.haml
.container
  = render 'search_form'
- if @results.photos
  = render 'pagination', results: @results
  - @results.photos.each do |photo|
    = render 'preview', photo: photo

  = render 'pagination', results: @results

app/views/search/show.html.haml
= image_tag @photo.url(:large)

%h2
  = @photo.try(:title)

%table.table.table-striped
  - if @photo.try(:camera)
    %tr
      %td Camera
      %td
      = @photo.try(:camera)
  - if @photo.exif
    - @photo.exif.each do |row|
      %tr
        %td
          = row[:label]
        %td
          = row[:content]